name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      VITE_LOCAL_TEST: ${{ vars.VITE_LOCAL_TEST }}
      VITE_RESPONSE_DEV_URL: ${{ vars.VITE_RESPONSE_DEV_URL }}

    steps:
      - name: Deploy dev
        uses: ./.github/actions/deploy
        with:
          environment: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    env:
      VITE_LOCAL_TEST: ${{ vars.VITE_LOCAL_TEST }}
      VITE_RESPONSE_DEV_URL: ${{ vars.VITE_RESPONSE_PROD_URL }}

    steps:
      - name: Deploy prod
        uses: ./.github/actions/deploy
        with:
          environment: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2