name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      VITE_LOCAL_TEST: ${{ vars.VITE_LOCAL_TEST }}
      VITE_RESPONSE_URL: ${{ vars.VITE_RESPONSE_URL }}
      VITE_AUTH0_CLIENT_ID: ${{vars.VITE_AUTH0_CLIENT_ID}}
      VITE_COGNITO_AUTHORITY: ${{vars.VITE_COGNITO_AUTHORITY}}
      VITE_COGNITO_DOMAIN: ${{vars.VITE_COGNITO_DOMAIN}}

    steps:
      - uses: actions/checkout@v4
      - name: Deploy dev
        uses: ./.github/actions/deploy
        with:
          environment: dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: prod
    env:
      VITE_LOCAL_TEST: ${{ vars.VITE_LOCAL_TEST }}
      VITE_RESPONSE_URL: ${{ vars.VITE_RESPONSE_URL }}
      VITE_AUTH0_CLIENT_ID: ${{vars.VITE_AUTH0_CLIENT_ID}}
      VITE_COGNITO_AUTHORITY: ${{vars.VITE_COGNITO_AUTHORITY}}
      VITE_COGNITO_DOMAIN: ${{vars.VITE_COGNITO_DOMAIN}}

    steps:
      - uses: actions/checkout@v4
      - name: Deploy prod
        uses: ./.github/actions/deploy
        with:
          environment: prod
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2